version: '3'
services:
  portainer:
    image: portainer/portainer:latest
    container_name: inethi-portainer
    volumes:
      - "${DOCKER_SOCK_MOUNT}:/var/run/docker.sock"
      - "${PORTAINER_VOLUME}:/data"
    restart: always
    ports:
    - 9000:9000
    networks:
      default:
        ipv4_address: "${PORTAINER_IPV4}"

  netdata:
    image: netdata/netdata:latest
    container_name: inethi-netdata
    ports:
      - 19999:19999
    restart: always
    networks:
      default:
        ipv4_address: "${NETDATA_IPV4}"
networks:
  default:
    external:
      name: "${PERFORMANCE_NETWORK}"
